[package]
name = "rostaller"
edition = "2021"
exclude = ["index.node"]

[lib]
path = "./type_exporter/lib.rs"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
full_moon = { version = "1", features = ["luau"] }
log = "0.4"
serde = "1"
serde_json = "1"
neon = "1"
