name: Upload Zip Files to Release

on:
  release:
    types: [published]

jobs:
  release-zip:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Download repository
      uses: actions/checkout@v4

    - name: Install Node
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: |
        npm install

    - name: Compile and build
      run: |
        ./node_modules/.bin/esbuild --platform=node --bundle --format=cjs --define:import.meta.url=_importMetaUrl "--banner:js=const _importMetaUrl = require('url').pathToFileURL(__filename)" --outfile=rostaller.js ./src/index.js
        ./node_modules/.bin/pkg --no-bytecode --public --targets latest-win,latest-macos,latest-macos-arm64,latest-linux,latest-linux-arm64 --public-packages '*' --out-path bin rostaller.js

    - name: Get release
      id: get_release
      uses: bruceadams/get-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Zip
      run: |
        cd bin
        mv rostaller-win-x64.exe rostaller.exe
        zip rostaller-${{ steps.get_release.outputs.tag_name }}-windows-x64.zip rostaller.exe ../LICENSE
        mv rostaller-macos-x64 rostaller
        chmod +x rostaller
        zip rostaller-${{ steps.get_release.outputs.tag_name }}-macos-x64.zip rostaller ../LICENSE
        mv rostaller-macos-arm64 rostaller
        chmod +x rostaller
        zip rostaller-${{ steps.get_release.outputs.tag_name }}-macos-arm64.zip rostaller ../LICENSE
        mv rostaller-linux-x64 rostaller
        chmod +x rostaller
        zip rostaller-${{ steps.get_release.outputs.tag_name }}-linux-x64.zip rostaller ../LICENSE
        mv rostaller-linux-arm64 rostaller
        chmod +x rostaller
        zip rostaller-${{ steps.get_release.outputs.tag_name }}-linux-arm64.zip rostaller ../LICENSE

    - name: Upload
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          bin/rostaller-${{ steps.get_release.outputs.tag_name }}-windows-x64.zip
          bin/rostaller-${{ steps.get_release.outputs.tag_name }}-macos-x64.zip
          bin/rostaller-${{ steps.get_release.outputs.tag_name }}-macos-arm64.zip
          bin/rostaller-${{ steps.get_release.outputs.tag_name }}-linux-x64.zip
          bin/rostaller-${{ steps.get_release.outputs.tag_name }}-linux-arm64.zip
